name: PIV1periodwaves
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.6
  - notebook>5.2
  - jupyter_dashboards
  - jupyter_dashboards_bundlers
  - matplotlib
  - openpiv
  - opencv
  - cv2
  - ipywidgets=7
  - numpy
  - scikit-image
